version: '3.3'
services:
  parsedmarc:
    build: ./parsedmarc/
    depends_on:
      - elasticsearch
      - grafana
    restart: on-failure
    networks:
      - dmarc_anal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8@sha256:2fe49bcdae9b623f1a38f979bfe51d2d7df94515dba731b1e1be9932349e1374
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - dmarc_anal

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dmarc_anal

volumes:
  es_data: {}
  grafana_data: {}

networks:
  dmarc_anal:
    driver: bridge
